; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = ttgo-t-beam-v1_2

extra_configs =
	common_settings.ini
  	variants/*/*.ini
	variants/*/*/platformio.ini
	variants/*/diy/*/platformio.ini
	src/graphics/niche/InkHUD/PlatformioConfig.ini
[env]
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
test_build_src = true
extra_scripts =
	pre:bin/platformio-pre.py
	bin/platformio-custom.py
	post:extra_scripts/nrf54l15_linker.py

[environmental_base]
extends = env
build_flags =
build_src_filter =
lib_deps =

[environmental_extra]
extends = env
build_flags =
build_src_filter =
lib_deps =

[arduino_base]
extends = env
build_flags =
build_src_filter =
lib_deps =

[radiolib_base]
extends = env
build_flags =
build_src_filter =
lib_deps =

[env:esp32]
extends = env
platform = espressif32 @ 6.12.0
board_build.partitions = huge_app.csv
monitor_filters = esp32_exception_decoder
board_build.embed_files =
	data_embed/index.html.gz
	data_embed/style.css.gz
	data_embed/script.js.gz
	data_embed/bootstrap.css.gz
	data_embed/bootstrap.js.gz
	data_embed/favicon.png.gz
extra_scripts =
	pre:tools/compress.py
debug_tool = esp-prog

[env:nrf52840_base]
extends = env
platform = nordicnrf52
build_flags = -D NRF52840_XXAA

[inkhud]
extends = env
build_flags =
build_src_filter =
lib_deps =

[env:t-echo-plus_custom]
extends = env
platform = nordicnrf52

; Custom metadata fields (not PlatformIO options):
; hw_model = 
; hw_model_slug = 
; architecture = 
; actively_supported = 
; support_level = 
; display_name = 
; images = 
; tags = 
; requires_dfu =
