[env:ttgo_t_deck_pro]
extends = env
platform = espressif32 @ 6.3.1
board_build.partitions = huge_app.csv
monitor_filters = esp32_exception_decoder
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.embed_files =
	data_embed/index.html.gz
	data_embed/style.css.gz
	data_embed/script.js.gz
	data_embed/bootstrap.css.gz
	data_embed/bootstrap.js.gz
	data_embed/favicon.png.gz
extra_scripts =
	pre:tools/compress.py
debug_tool = esp-prog
build_flags =
	${common.build_flags}
	${common.usb_flags}
	-D TTGO_T_DECK_PRO
	-D BOARD_HAS_PSRAM
	-D RADIOLIB_EXCLUDE_LR11X0=1
	-D RADIOLIB_EXCLUDE_SX127X=1
	-D RADIOLIB_EXCLUDE_SX128X=1
lib_deps =
	${common.lib_deps}
	ZinggJM/GxEPD2 @ 1.6.9
	adafruit/Adafruit TCA8418 @ 1.0.2
	lewisxhe/XPowersLib @ 0.3.3
